services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/event_reservation?schema=public
      - REDIS_URL=redis://redis:6379
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/event_reservation?schema=public
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=event_reservation
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
      image: redis:alpine
      ports:
            - "6379:6379"
      environment:
            - DATABASE_URL=postgresql://user:password@db:5432/event_reservation?schema=public
            - REDIS_URL=redis://redis:6379
            - REDIS_PORT=6379
            - REDIS_HOST=redis


volumes:
  postgres_data:
